### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mwhittaker** [mwhittaker/frankenpaxos#1]
- [ ] Add very direct unit tests that step through a particular execution of the algorithm.
- [ ] Add an animation mode in which a pre-selected sequence of events occurs. 
- [x] Have JS animation spit out the steps that it performed for replay.
- [x] Make sure clients don't call actor methods directly (it's not thread safe)
- [ ] Add timer animations to js apps. 
- [x] Add randomized unit tests that check for an invariant, like quickcheck. 
- [x] Integrate futures instead of having callbacks.
- [x] Add a README. 
- [x] Separate zeno code from FrankenPaxos code. 
- [ ] Integrate prometheus. 
- [ ] Add persistence abstraction so that algorithms can persist state.
- [ ] Enable a javascript application to be reset by clicking a button. 
- [ ] Have nodes run http servers with their status. 
- [x] Add the ability to fail a node in a javascript app.
- [ ] Add the ability to cut a link in a javascript app. 
- [ ] Show the number of messages sent across each link and the number of messages processed by each node. 
- [ ] Add the ability to speed up or slow down time in a javascript app.
- [ ] Add the ability to go backwards through time a javascript app.
- [x] Clean up java logging. 
- [ ] Share multiple actors on the same address. 
- [ ] Have actors export html directly. This way, they can expose their private fields to the JS animation.
- [ ] Fix bug where animation stalls when tab is not active.
